title: Today I Learned with Michał Kalbarczyk
author: Michał Kalbarczyk
description: Today I Learned with Michał Kalbarczyk
url: "https://til.fazibear.me"
ga: "G-4093L52QLW"
nav_logo: til.fazibear.me
primary_color: "#9462ff"

permalink: /:title

theme: "fazibear.me"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "terminal"
